apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitor
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'kubernetes'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'chat-app-backend'
        static_configs:
          - targets: ['backend-service:5001']

