apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatapp-ingress
  namespace: chat-app

spec:
  ingressClassName: nginx
  rules:
      http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80
